version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: holesky
        P2P_TCP_PORT: 14503
        P2P_UDP_PORT: 14503
    ports:
      - 14503:14503/tcp
      - 14503:14503/udp
    environment:
      CORSDOMAIN: "*"
  validator:
    build:
      args:
        NETWORK: holesky
        BEACON_RPC_PROVIDER: "beacon-chain.prysm-holesky.dappnode:4000"
        BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-holesky.dappnode:3500"
