version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: lukso
        P2P_TCP_PORT: 12603
        P2P_UDP_PORT: 12603
    ports:
      - 12603:12603/tcp
      - 12603:12603/udp
    environment:
      CORSDOMAIN: "http://prysm-lukso.dappnode"
      MIN_SYNC_PEERS: "1"
      MAX_PEERS: "250"
      SUBSCRIBE_ALL_SUBNETS: "true"
  validator:
    build:
      args:
        NETWORK: lukso
        BEACON_RPC_PROVIDER: "beacon-chain.prysm-lukso.dappnode:4000"
        BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-lukso.dappnode:3500"
